name: def
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - matplotlib-venn
  - statsmodels
  - jupyterlab
  - scikit-learn
  - scipy
  - seaborn
  - ipywidgets
  - pytables
  - tqdm
