name: def
channels:
  - conda-forge
  - bioconda
dependencies:
  - matplotlib-venn
  - jupyterlab
  - fa2
  - ipywidgets
  - pytables
  - scanpy
  - numpy
  - numba
  - pandas
  - python
  - statsmodels
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - umap-learn
  - yaml
  - joblib
